[
  {
    id: 29286,
    name: 'GIF',
    code: 'SP QUÀ KHUYẾN MÃI',
    level: 0,
    parentId: null,
  },
  {
    id: 29287,
    name: 'Taisancodinh',
    code: 'Tài sản cố định - Vật dụng',
    level: 0,
    parentId: null,
  },
  {
    id: 29288,
    name: 'GOIBAOHANH',
    code: 'GOIBAOHANH',
    level: 0,
    parentId: null,
  },
  {
    id: 29289,
    name: 'SIMTHE',
    code: 'SIMTHE',
    level: 0,
    parentId: null,
  },
  {
    id: 29290,
    name: 'PHỤ KIỆN COMBO',
    code: 'PHỤ KIỆN COMBO',
    level: 0,
    parentId: null,
  },
  {
    id: 29291,
    name: 'Combo Miếng dán',
    code: 'Combo Miếng dán',
    level: 1,
    parentId: 29290,
  },
  {
    id: 29292,
    name: 'Combo Cáp Sạc',
    code: 'Combo Cáp Sạc',
    level: 1,
    parentId: 29290,
  },
  {
    id: 29293,
    name: 'ĐIỆN MÁY GIA DỤNG',
    code: 'ĐIỆN MÁY GIA DỤNG',
    level: 0,
    parentId: null,
  },
  {
    id: 29294,
    name: 'Linh Kiện',
    code: 'Linh Kiện',
    level: 0,
    parentId: null,
  },
  {
    id: 29295,
    name: 'Dịch vụ',
    code: 'Dịch vụ',
    level: 0,
    parentId: null,
  },
  {
    id: 29296,
    name: 'Máy Tính - Laptop',
    code: 'Máy Tính - Laptop',
    level: 0,
    parentId: null,
  },
  {
    id: 29297,
    name: 'Thẻ Cào - Sim Card',
    code: 'Thẻ Cào - Sim Card',
    level: 0,
    parentId: null,
  },
  {
    id: 29298,
    name: 'Phụ Kiện',
    code: 'Phụ Kiện',
    level: 0,
    parentId: null,
  },
  {
    id: 29299,
    name: 'Điện Thoại - Tablet',
    code: 'Điện Thoại - Tablet',
    level: 0,
    parentId: null,
  },
];
