export const productsData = [
  {
    product_id: '50000189',
    product: 'Thang Test SP 18',
    product_status: 'A',
    tax_name: null,
    tax_ids: null,
    price: 0,
    whole_price: 0,
    list_price: 300000,
    collect_price: 0,
    product_code: 'Thang Test SP 18',
    product_type: '3',
    combo_amount: 2,
    barcode: '3000000000191',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: null,
    slug: 'thang-test-sp-18',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [],
  },
  {
    product_id: '50000184',
    product: 'Thang Test SP 19',
    product_status: 'A',
    tax_name: null,
    tax_ids: null,
    price: 0,
    whole_price: 0,
    list_price: 300000,
    collect_price: 0,
    product_code: 'Thang Test SP 19',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000186',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451460,
    parent_product_id: null,
    slug: 'thang-test-sp-19',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [],
  },
  {
    product_id: '50000183',
    product: 'Thang Test SP 17',
    product_status: 'A',
    tax_name: null,
    tax_ids: null,
    price: 0,
    whole_price: 0,
    list_price: 200000,
    collect_price: 0,
    product_code: 'Thang Test SP 17',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000185',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451465,
    parent_product_id: null,
    slug: 'thang-test-sp-17',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902209,
      },
    ],
  },
  {
    product_id: '50000178',
    product: 'Thang Test SP 16',
    product_status: 'A',
    tax_name: null,
    tax_ids: null,
    price: 0,
    whole_price: 0,
    list_price: 200000,
    collect_price: 0,
    product_code: 'Thang Test SP 16',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000180',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: null,
    slug: 'thang-test-sp-16',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902209,
      },
    ],
  },
  {
    product_id: '50000173',
    product: 'Thang Test SP 14',
    product_status: 'A',
    tax_name: null,
    tax_ids: null,
    price: 200000,
    whole_price: 200000,
    list_price: 200000,
    collect_price: 200000,
    product_code: 'Thang Test SP 14',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000175',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: null,
    slug: 'thang-test-sp-14',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [],
  },
  {
    product_id: '50000190',
    product: 'Thang Test SP 18 - Đỏ - Used',
    product_status: 'A',
    tax_name: '- Đỏ - Used',
    tax_ids: '-RED-DDVC',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 18-RED-DDVC',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000192',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000189',
    slug: 'thang-test-sp-18-red',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331990,
      },
      {
        feature_code: 13,
        variant_code: 902209,
      },
    ],
  },
  {
    product_id: '50000191',
    product: 'Thang Test SP 18 - Đỏ - Demo',
    product_status: 'A',
    tax_name: '- Đỏ - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 18-RED-DDVDemo',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000193',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000189',
    slug: 'thang-test-sp-18-red-demo',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331991,
      },
      {
        feature_code: 14,
        variant_code: 902177,
      },
    ],
  },
  {
    product_id: '50000192',
    product: 'Thang Test SP 18 - Đen - Used',
    product_status: 'A',
    tax_name: '- Đen - Used',
    tax_ids: '-RED-DDVC',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 18-RED-DDVC',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000194',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000189',
    slug: 'thang-test-sp-18-red-ddvc-used',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902209,
      },
    ],
  },
  {
    product_id: '50000193',
    product: 'Thang Test SP 18 - Đen - Demo',
    product_status: 'A',
    tax_name: '- Đen - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 18-RED-DDVDemo',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000195',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000189',
    slug: 'thang-test-sp-18-den-demo',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902207,
      },
    ],
  },
  {
    product_id: '50000205',
    product: 'Thang Test SP 22 - Đen - Demo',
    product_status: 'A',
    tax_name: '- Đen - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test Phu kien 22-RED-DDVDemo',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000195',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000178',
    slug: 'thang-test-sp-22',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902207,
      },
    ],
  },
  {
    product_id: '50000206',
    product: 'Thang Test Phu Kien 23 - Đen - Demo',
    product_status: 'A',
    tax_name: '- Đen - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test Phu kien 22-RED-DDVDemo',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000195',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000178',
    slug: 'thang-test-phukien-23',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,
    height: 0,
    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902207,
      },
    ],
  },
  {
    product_id: '50000185',
    product: 'Thang Test SP 19 - Đỏ - Demo',
    product_status: 'A',
    tax_name: '- Đỏ - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 19-RED-DDVDemo',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000187',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451460,
    parent_product_id: '50000184',
    slug: 'thang-test-sp-19-do-demo',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902207,
      },
    ],
  },
  {
    product_id: '50000186',
    product: 'Thang Test SP 19 - Đỏ - New',
    product_status: 'A',
    tax_name: '- Đỏ - New',
    tax_ids: '-RED-DDVNew',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 19-RED-DDVNew',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000188',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451460,
    parent_product_id: '50000184',
    slug: 'thang-test-sp-19-de-new',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902210,
      },
    ],
  },
  {
    product_id: '50000187',
    product: 'Thang Test SP 19 - Đen - Demo',
    product_status: 'A',
    tax_name: '- Đen - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 19-RED-DDVDemo',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000189',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451460,
    parent_product_id: '50000184',
    slug: 'thang-test-sp-19-den-demo',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902207,
      },
    ],
  },
  {
    product_id: '50000188',
    product: 'Thang Test SP 19 - Đen - New',
    product_status: 'A',
    tax_name: '- Đen - New',
    tax_ids: '-RED-DDVNew',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 19-RED-DDVNew',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000190',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451460,
    parent_product_id: '50000184',
    slug: 'thang-test-sp-19-den-new',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902210,
      },
    ],
  },
  {
    product_id: '50000174',
    product: 'Thang Test SP 14 - Đỏ - Demo',
    product_status: 'A',
    tax_name: '- Đỏ - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 200000,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 14-RED-DDVDemo',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000176',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000173',
    slug: 'thang-test-sp-14-do-demo',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902207,
      },
    ],
  },
  {
    product_id: '50000175',
    product: 'Thang Test SP 14 - Đỏ - Used',
    product_status: 'A',
    tax_name: '- Đỏ - Used',
    tax_ids: '-RED-DDVC',
    price: 200000,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 14-RED-DDVC',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000177',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000173',
    slug: 'thang-test-sp-14-do-used',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902209,
      },
    ],
  },
  {
    product_id: '50000176',
    product: 'Thang Test SP 14 - Đen - Demo',
    product_status: 'A',
    tax_name: '- Đen - Demo',
    tax_ids: '-RED-DDVDemo',
    price: 200000,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 14-RED-DDVDemo',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000178',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000173',
    slug: 'thang-test-sp-14-den-demo',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902207,
      },
    ],
  },
  {
    product_id: '50000177',
    product: 'Thang Test SP 14 - Đen - Used',
    product_status: 'A',
    tax_name: '- Đen - Used',
    tax_ids: '-RED-DDVC',
    price: 200000,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 14-RED-DDVC',
    product_type: '4',
    combo_amount: 2,
    barcode: '3000000000179',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000173',
    slug: 'thang-test-sp-14-den-used',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902209,
      },
    ],
  },
  {
    product_id: '50000179',
    product: 'Thang Test SP 16 - Đỏ - Likenew',
    product_status: 'A',
    tax_name: '- Đỏ - Likenew',
    tax_ids: '-RED-DDVB',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 16-RED-DDVB',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000181',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000178',
    slug: 'thang-test-sp-16-do-likenew',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 902208,
      },
    ],
  },
  {
    product_id: '50000180',
    product: 'Thang Test SP 16 - Đỏ - test tình trạng',
    product_status: 'A',
    tax_name: '- Đỏ - test tình trạng',
    tax_ids: '-RED-test-status',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 16-RED-test-status',
    product_type: '2',
    combo_amount: 2,
    barcode: '3000000000182',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000178',
    slug: 'thang-test-sp-16-do-test-tinh-trang',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 1331963,
      },
    ],
  },
  {
    product_id: '50000181',
    product: 'Thang Test SP 16 - Đen - Likenew',
    product_status: 'A',
    tax_name: '- Đen - Likenew',
    tax_ids: '-RED-DDVB',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 16-RED-DDVB',
    product_type: '3',
    combo_amount: 2,
    barcode: '3000000000183',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000178',
    slug: 'thang-test-sp-16-den-likenew',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331993,
      },
      {
        feature_code: 13,
        variant_code: 902208,
      },
    ],
  },
  {
    product_id: '50000182',
    product: 'Thang Test SP 16 - Đen - test tình trạng',
    product_status: 'A',
    tax_name: '- Đen - test tình trạng',
    tax_ids: '-RED-test-status',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 16-RED-test-status',
    product_type: '3',
    combo_amount: 2,
    barcode: '3000000000184',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: '50000178',
    slug: 'thang-test-sp-16-den-test-tinh-trang',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331993,
      },
      {
        feature_code: 13,
        variant_code: 1331963,
      },
    ],
  },
  {
    product_id: '50000250',
    product: 'Thang Test SP 50 - Hồng - test tình trạng',
    product_status: 'A',
    tax_name: '- Hồng - test tình trạng',
    tax_ids: '-PINK-test-status',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Thang Test SP 50-PINK-test-status',
    product_type: '1',
    combo_amount: 2,
    barcode: '3000000000199',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: null,
    slug: 'thang-test-sp-50-hong-test',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [
      {
        feature_code: 34,
        variant_code: 1331992,
      },
      {
        feature_code: 13,
        variant_code: 1331963,
      },
    ],
  },
  {
    product_id: '50000251',
    product: 'Test SP Dich vu',
    product_status: 'A',
    tax_name: '- Hồng - test tình trạng',
    tax_ids: '-PINK-test-status',
    price: 0,
    whole_price: 0,
    list_price: 0,
    collect_price: 0,
    product_code: 'Test SP Dich vu',
    product_type: '4',
    combo_amount: 0,
    barcode: '3000000000200',
    age_warning_message: '',
    status: 'A',
    display_at: '2022-02-24',
    category_id: 451459,
    parent_product_id: null,
    slug: 'thang-test-sp-service',
    promo_text: '',
    short_description: '',
    page_title: '',
    meta_description: '',
    alias: '',
    weight: 0,
    length: 0,
    width: 0,

    images: [
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/iphone-11-64gb-chinh-hang_3.jpg',
      'https://cdn.didongviet.vn/pub/media/catalog/product//i/p/ip12.jpg',
    ],
    product_features: [],
  },
];
