export const logModules = {
  1: 'Tạo đơn hàng',
  2: 'Cập nhật đơn hàng',
  3: 'Tạo khách hàng',
  4: 'Cập nhật khách hàng',
  5: 'Tạo thuộc tính sản phẩm',
  6: 'Cập nhật thuộc tính sản phẩm',
  7: 'Tạo danh mục',
  8: 'Cập nhật danh mục',
  9: 'Đồng bộ điểm khách hàng',
  10: 'Đồng bộ lịch sử tích điểm',
  11: 'Tạo sản phẩm',
  12: 'Cập nhật sản phẩm',
  13: 'Tạo sản phẩm Combo',
  14: 'Cập nhật sản phẩm combo',
  15: 'Tạo bộ phụ kiện tặng kèm',
  16: 'Cập nhật bộ phụ kiện tặng kèm',
  17: 'Tạo bộ phụ kiện khuyến mãi',
  18: 'Cập nhật bộ phụ kiện khuyến mãi',
  19: 'Tạo gói bảo hành',
  20: 'Cập nhật gói bảo hành',
  21: 'Tạo mới chương trình thu cũ',
  22: 'Cập nhật chương trình thu cũ',
  23: 'Tạo phiếu thu cũ',
  24: 'Cập nhật phiếu thu cũ',
};

export const logSources = {
  1: 'Appcore',
  2: 'CMS',
  3: 'Không xác định',
};
