export enum PageDetailType {
  'normal' = 1,
  'BOX_PRODUCT' = 'BOX_PRODUCT',
  'FLASH_SALE' = 'FLASH_SALE',
  'BANNER' = 'BANNER',
  'MENU' = 'MENU',
  'BOX_MENU' = 'BOX_MENU',
  'IMAGE_BACKGROUND' = 'IMAGE_BACKGROUND',
  'COLOR_BACKGROUND' = 'COLOR_BACKGROUND',
}

export enum PageDetailValueType {
  'LIST_PRODUCTS' = 'LIST_PRODUCTS',
  'LIST_TABS' = 'LIST_TABS',
  'BACKGROUND' = 'BACKGROUND',
  'LIST_COMPANY' = 'LIST_COMPANY',
  'LIST_PRICE' = 'LIST_PRICE',
  'IMAGE_BACKGROUND' = 'IMAGE_BACKGROUND',
  'COLOR_BACKGROUND' = 'COLOR_BACKGROUND',
}
