export class ProductDescriptionsEntity {
  product_description_id: number = 0;
  product_id: string = '0';
  lang_code: string = '';
  product: string = '';
  shortname: string = '';
  alias: string = '';
  product_core_name: string = '';
  short_description: string = '';
  full_description: string = '';
  meta_keywords: string = '';
  meta_description: string = '';
  search_words: string = '';
  page_title: string = '';
  age_warning_message: string = '';
  promo_text: string = '';
  other_info: string = '';
  product_hover: string = '';
  promotion_note: string = '';
  promotion_info: string = '';
  online_gifts: string = '';
  meta_image: string = '';
}
