import { convertToMySQLDateTime } from 'src/utils/helper';
import { UserMenuEntity } from './userMenu.entity';
export class UserEntity {
  user_id: number;
  status: string = 'A';
  user_type: string = '';
  user_login: string = '';
  referer: string = '';
  is_root: string = '';
  company_id: number = 0;
  last_login: number = 0;
  created_at: Date = new Date();
  password: string = '';
  salt: string = '';
  firstname: string = '';
  lastname: string = '';
  company: string = '';
  email: string = '';
  phone: string = '';
  fax: string = '';
  url: string = '';
  tax_exempt: string = '';
  lang_code: string = 'vi';
  birthday: Date = new Date();
  purchase_timestamp_from: Date = new Date();
  purchase_timestamp_to: Date = new Date();
  responsible_email: string = '';
  last_passwords: string = '';
  password_change_timestamp: number = 0;
  api_key: string = '';
  janrain_identifier: string = '';
  verify_token: string = '';
  verify_token_exp: Date = new Date();
  otp: number = 0;
  otp_incorrect_times: number = 0;
}
