import { convertToMySQLDateTime } from 'src/utils/helper';
import { UserMenuEntity } from './userMenu.entity';
export class UserEntity {
  user_id: number = 0;
  status: string = 'A';
  user_type: string = 'C';
  user_login: string = 'SYSTEM';
  user_appcore_id: number = 0;
  is_root: string = '';
  company_id: number = 0;
  store_id: number = 0;
  last_login: number = 0;
  created_at: string = convertToMySQLDateTime();
  password: string = '';
  salt: string = '';
  firstname: string = '';
  lastname: string = '';
  company: string = '';
  email: string = '';
  phone: string = '';
  fax: string = '';
  url: string = '';
  tax_exempt: string = '';
  lang_code: string = 'vi';
  birthday: string = convertToMySQLDateTime();
  purchase_timestamp_from: string = convertToMySQLDateTime();
  purchase_timestamp_to: string = convertToMySQLDateTime();
  responsible_email: string = '';
  last_passwords: string = '';
  password_change_timestamp: number = 0;
  api_key: string = '';
  janrain_identifier: string = '';
  type: string = '1';
}
