export const cacheKeys = {
  catalog: (queryParameters = '') => `catalog${queryParameters}`,
  banner: (bannerId) => `banner-${bannerId}`,
  banners: (params) => `banners${params}`,
  productByCategorySlug: (categorySlug) => `cat-${categorySlug}`,
  flashSaleWebsite: `flash-sale-website`,
  category: (categoryId) => `category-${categoryId}`,
  categories: (params) => `categories${params}`,
  categoryLevel: (level) => `categories-level-${level}`,
  product: (productId) => `product-${productId}`,
  products: (params) => `products${params}`,
  bannerLocations: `banner-locations`,
  bannerTargets: (params) => `banner-targets${params}`,
  carts: (params) => `carts${params}`,
  cartByUserId: (userId) => `cart-${userId}`,
  dashboardOverview: `dashboard-overview`,
  flashSale: (id) => `flashSale-${id}`,
  flashSales: (params) => `flashSale${params}`,
  search: (q) => `search-${q}`,
  functs: 'functs',
  page: (id) => `page-${id}`,
  stockAmount: (productId) => `stock-amount-${productId}`,
};

export const cacheTables = {
  category: 'Category',
  product: 'Product',
  productFeature: 'Product Feature',
  sticker: 'Sticker',
  banner: 'Banner',
  cart: 'Cart',
  dashboard: 'Dashboard',
  flashSale: 'Flash sale',
  search: 'Search',
  functs: 'Functs',
  page: 'Page',
  stockAmount: 'Stock Amount',
};

export const prefixCacheKey = {
  categories: 'categories',
  categoriesLevel: 'categories-level',
  products: 'products',
  category: 'category',
  categoryId: (categoryId) => `category-${categoryId}`,
  banner: 'banner',
  bannerId: 'banner',
  product: 'product',
  productId: (productId) => `product-${productId}`,
  banners: 'banners',
  bannerTargets: 'banner-targets',
  cart: 'cart',
  carts: 'carts',
  dashboard: 'dashboard',
  flashSale: 'flashSale',
  search: 'search',
  functs: 'functs',
  stockAmount: 'stock-amount',
  pageId: (pageId) => `page-${pageId}`,
};
